briefme_invoices/urls.py
from django.urls import path
from django.contrib.admin.views.decorators import staff_member_required

from .views import (
    InvoicesListView,
    UpdateInvoicingInfoView,
    DisplayInvoiceView,
    DownloadInvoiceView,
)


app_name = "invoices"


urlpatterns = [
    path("", InvoicesListView.as_view(), name="list"),
    path("informations/", UpdateInvoicingInfoView.as_view(), name="update_info"),
    path(
        "<int:transaction_id>/",
        staff_member_required(DisplayInvoiceView.as_view()),
        name="detail",
    ),
    path("<int:transaction_id>/download/", DownloadInvoiceView.as_view(), name="download"),
]

briefme_invoices/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.functional import cached_property
from model_utils.models import TimeStampedModel

from briefme_core.subscription.chargify import ChargifyHelper

from .utils import extract_invoice_data


class InvoiceMismatch(Exception):
    pass


class InvoiceManager(models.Manager):
    def get_or_create_from_chargify(self, transaction_id, user):
        try:
            invoice = self.get_queryset().get(transaction_id=transaction_id, user=user)
        except self.model.DoesNotExist:
            invoice = self.create_from_chargify(transaction_id, user)

        return invoice

    def create_from_chargify(self, transaction_id, user):
        chargify = ChargifyHelper()
        transaction = chargify.get_transaction(transaction_id)

        # ensure requested transaction belongs to the user
        customer = chargify.get_customer_by_reference(user.pk)
        if customer["id"] != transaction["customer_id"]:
            raise InvoiceMismatch()

        invoice = self.model(raw_transaction=transaction, user=user)
        invoice.save()

        return invoice


class Invoice(TimeStampedModel):
    statement_id = models.CharField(max_length=100, unique=True, blank=True, null=True)
    transaction_id = models.CharField(max_length=100, unique=True, blank=True, null=True)
    raw_statement = models.JSONField(blank=True, null=True)
    raw_transaction = models.JSONField(null=True)
    billing_info = models.JSONField()
    vat_rate = models.FloatField()
    user = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, blank=False, null=True)
    objects = InvoiceManager()

    @cached_property
    def extracted_data(self):
        """For convenience, locally cache relevant data from raw transaction."""
        return extract_invoice_data(self.raw_transaction)

    @property
    def price_paid(self):
        return self.extracted_data["price_paid"]

    @property
    def product_name(self):
        return self.extracted_data["product"]

    @property
    def payment_date(self):
        return self.extracted_data["payment_date"]

    def get_sequence(self):
        """Generate unique sequence {INVOICES_PREFIX}-0000001."""
        left_filled_pk = str(self.pk).zfill(10)
        return f"{settings.INVOICES_PREFIX}-{left_filled_pk}"

    @property
    def price_excluding_vat(self):
        return self.price_paid / (1 + self.vat_rate / 100)

    @property
    def vat_amount(self):
        return self.price_paid - self.price_excluding_vat

    def _get_vat_rate(self):
        return 2.1

    def _serialize_billing_info(self):
        return {
            "last_name": self.user.last_name,
            "first_name": self.user.first_name,
            "organization": self.user.organization,
            "email": self.user.email,
            "address": self.user.address,
            "zip": self.user.zip,
            "city": self.user.city,
            "country": self.user.country,
        }

    def save(self, *args, **kwargs):
        if self.raw_statement:
            self.statement_id = self.raw_statement["id"]
        if self.raw_transaction:
            self.transaction_id = self.raw_transaction["id"]
        self.billing_info = self._serialize_billing_info()
        self.vat_rate = self._get_vat_rate()
        super().save(*args, **kwargs)

briefme_invoices/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth import get_user_model

from .countries import COUNTRIES


class UpdateInvoicingInfoForm(ModelForm):
    country = forms.ChoiceField(
        required=True,
        label="Pays",
        choices=COUNTRIES,
        widget=forms.Select(
            attrs={
                "class": "input-inner cursor cursor-pointer close overflow-hidden border border-grey-light bg-grey-verylight pt-8px pb-12px px-10px rounded-6 relative transition duration-300 ease-in-out w-full text-black-light h-48px"
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.Meta.required:
            self.fields[field].required = True

    class Meta:
        model = get_user_model()
        fields = [
            "first_name",
            "last_name",
            "organization",
            "address",
            "zip",
            "city",
            "country",
        ]
        required = [
            "address",
            "zip",
            "city",
            "country",
        ]

    def clean(self):
        cleaned_data = super().clean()
        last_name = cleaned_data.get("last_name")
        first_name = cleaned_data.get("first_name")
        organization = cleaned_data.get("organization")

        if not (organization or (first_name and last_name)):
            raise forms.ValidationError(
                "Le nom et prénom ou l'organisation doivent être renseignés."
            )

briefme_invoices/views.py
from django.views.generic import TemplateView, UpdateView, DetailView
from braces.views import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django_weasyprint import WeasyTemplateResponseMixin
from django.conf import settings
from django.http import Http404

from .models import Invoice, InvoiceMismatch
from .forms import UpdateInvoicingInfoForm
from .utils import get_invoices_data_for, UncoveredInvoicing


class DisplayInvoiceView(LoginRequiredMixin, DetailView):
    """Given a Chargify transaction, get (or create) an invoice object and display it."""

    template_name = "invoices/detail.html"

    def get_object(self, queryset=None):
        user = self.request.user
        transaction_id = self.kwargs.get("transaction_id")
        try:
            return Invoice.objects.get_or_create_from_chargify(transaction_id, user)
        except InvoiceMismatch:
            raise Http404


class DownloadInvoiceView(WeasyTemplateResponseMixin, DisplayInvoiceView):
    """Render a PDF version of an invoice, out of HTML."""

    pdf_attachment = settings.INVOICES_PDF_ATTACHMENT

    def get_pdf_filename(self):
        sequence = self.object.get_sequence()
        return f"facture-{sequence}.pdf"


class InvoicesListView(LoginRequiredMixin, TemplateView):
    """Display a list of downloadable paid invoices."""

    template_name = "invoices/list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        try:
            context["invoices"] = get_invoices_data_for(user)
        except UncoveredInvoicing:
            messages.error(
                self.request,
                "Une erreur est survenue. Merci de bien vouloir nous contacter.",
            )
        return context


class UpdateInvoicingInfoView(LoginRequiredMixin, UpdateView):
    """Update billing information."""

    template_name = "invoices/update_info.html"
    form_class = UpdateInvoicingInfoForm

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        url_invoices = reverse("invoices:list")
        messages.success(
            self.request,
            f"<strong>Vos informations de facturation ont été mises à jour.</strong>"
            f"<br><a href='{url_invoices}'>Voir mes factures</a>",
        )
        return reverse("invoices:update_info")

briefme_invoices/templates/invoices/detail.html
{% load static countries %}
<!doctype html>{# CAUTIOUS - this HTML file is used to generated PDF invoices #}
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title>{% block brand %}BRAND{% endblock %} - facture {{ object.get_sequence }}</title>
        <link rel="stylesheet" href="{% static 'briefme_invoices/css/invoices_detail.css' %}">
    </head>
    <body>
        {% block logo %}LOGO{% endblock %}

        <dl id="informations">
          <dt>Facture</dt>
          <dd>{{ object.get_sequence }}</dd>
          <dt>Date</dt>
          <dd>{{ object.created|date:"DATE_FORMAT" }}</dd>
        </dl>

        <aside>
          <address id="from">
            &nbsp;
          </address>

          <address id="to">
            {% if object.billing_info.last_name %}{{ object.billing_info.first_name|upper }} {{ object.billing_info.last_name|upper }}{% endif %}
            {% if object.billing_info.organization %}{{ object.billing_info.organization|upper }}{% endif %}
            {{ object.billing_info.address|upper }}
            {{ object.billing_info.zip|upper }} {{ object.billing_info.city|upper }}
            {% get_country object.billing_info.country as country %} {{ country.name }}
          </address>
        </aside>

        <table>
            <thead>
                <tr>
                    <th>Nom du produit </th>
                    <th>Prix HT</th>
                    <th>TVA ({{ object.vat_rate }}%)  </th>
                    <th>Prix TTC</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ object.product_name }}</td>
                    <td>{{ object.price_excluding_vat|floatformat:2 }} €</td>
                    <td>{{ object.vat_amount|floatformat:2 }} € </td>
                    <td>{{ object.price_paid|floatformat:2 }} €</td>
                </tr>
            </tbody>
        </table>

        <p class="date">Paiement enregistré le {{ object.payment_date|date:"DATE_FORMAT" }}.</p>

        <footer>
            Brief.me. SAS au capital de 42 750 €, RCS Paris 807 526 603. Siège social : 14 rue de Thionville, 75019 Paris. Numéro de TVA intracommunautaire : FR68807526603.
        </footer>
    </body>
</html>

briefme_invoices/templates/invoices/includes/info.html
{% load invoices_tags %}

{% has_invoicing_information user as has_invoicing_info %}

{% if has_invoicing_info %}
    <p>Mon adresse de facturation:</p>

    <p>
        {{ user.get_full_name }}<br />
        {{ user.organization }}<br />
        {{ user.address }}<br />
        {{ user.zip }} {{ user.city }}<br />
        {{ user.get_country_display|upper }}<br />
        <a href="{% url 'invoices:update_info' %}">Mettre à jour</a><br>
        <a href="{% url 'invoices:list' %}">Consulter mes factures</a>
    </p>
{% else %}
    <p>
        Ajoutez vos informations de facturation pour accéder à vos factures.
        <a href="{% url 'invoices:update_info' %}">Compléter mes informations de facturation</a>
    </p>
{% endif %}

briefme_invoices/templates/invoices/list.html
{% load invoices_tags %}

{% if messages %}
    <ul>
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</section>
{% endif %}


<p>Voici le récapitulatif de vos derniers paiements :</p>


<ul>
    {% for invoice in invoices %}
        <li>{% if invoice.product %}{{ invoice.product }}{% else %}Abonnement{% endif %} - {{ invoice.payment_date|date:"DATE_FORMAT" }} - {{ invoice.price_paid|floatformat:2 }} € <a href="{% url 'invoices:download' invoice.transaction_id %}">Télécharger</a></li>
    {% empty %}
        <li>Aucune facture disponible. Les factures ne sont disponibles qu'une fois le paiement effectué.</li>
    {% endfor %}
</ul>

briefme_invoices/templates/invoices/update_info.html
{% load invoices_tags %}

{% if messages %}
    <ul>
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
</section>
{% endif %}


<form method="POST" action="?">

    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Mettre à jour</button>

    {% has_invoicing_information user as has_invoicing_info %}
    {% if has_invoicing_info %}
    <p>
        <a href="{% url 'invoices:list' %}">Voir mes factures</a>
    </p>
    {% endif %}

</form>